### ISSUE TITLE
Typo in edit_form_extension option

### ISSUE THREAD

**Issue by Schwierig** [akeneo-labs/CustomEntityBundle#110]
There is a typo in the `Pim\Bundle\CustomEntityBundle\Action\Rest\AbstractRestAction` class on line 157. `edit_fom_extension` should be `edit_form_extension`

**Comment by jmleroux** [comment]
Hello @Schwierig ,

On which version?
Ideally, PR are welcome ;)

Regards,

**Comment by jmleroux** [comment]
Good catch!
Fixed in #114

**Comment by jmleroux** [comment]
Merged
