### ISSUE TITLE
UI to manage a Reference Data

### ISSUE THREAD

**Issue by DomeRS93** [akeneo-labs/CustomEntityBundle#141]
Hello,

I think your "cookbook" has a lack of information at a couple of parts ...

https://docs.akeneo.com/2.1/design_pim/guides/create_a_reference_data_crud.html

Followed this "recipe" from the beginning, the result is that there is no route defined for "enrich/color".

My idea was to create this "enrich/color" in my routing.yml, which resulted in an 

> Unable to find the controller for path "/enrich/color/". The route is wrongly configured.

I also had to adjust the signatures for the entity to 
`public static function getSortOrderColumn() : string` - the ": string" is missing in the cookbook.

Also the custom_entities.yml "example" is missing the "service" tag. I copied the one from the "example" in the docs folder. Is this the problem?

Cheers
Dom

**Comment by jmleroux** [comment]
UI for reference data is part of Enterprise Edition under the name `Reference entities`.
