### ISSUE TITLE
New install on 2.1.5 missing new attributes: color, fabric...

### ISSUE THREAD

**Issue by nicolicioiul** [akeneo-labs/CustomEntityBundle#151]
I installed the module on akeneo 2.1.5 and the new reference data attributes are not available when I am trying to create a new attribute, autocommplete is empty.
But, on export, I have the newly added item from CLI.

Is there any to check that? I cleared the cache and restart all the services

**Comment by fitn** [comment]
Hello @nicolicioiul 

This is a problem linked to the PIM itself and not he CustomEntityBundle. Take a look at our configuration documentation here: https://docs.akeneo.com/2.1/manipulate_pim_data/catalog_structure/creating_a_reference_data.html#configuring-the-reference-data

It should fix your problem :)

Regards,

**Comment by nicolicioiul** [comment]
Fixed.
