### ISSUE TITLE
TranslatableEntities generate error when selecting values in product attribute

### ISSUE THREAD

**Issue by ptitkosmos** [akeneo-labs/CustomEntityBundle#180]
When selecting a value in product attribut, an error occured due to a wrong named options in the `findBySearchQB` function in the `TranslatableCustomEntityRepository`
> ->setParameter('localeCode', **_$options['dataLocale']_**);

`$options` values are : 
> Array
(
    [type] => code
    [limit] => 20
    [page] => 1
    **_[catalogLocale] => en_GB_**
)

Message : 
> Notice: Undefined index: dataLocale in /srv/pim/vendor/akeneo-labs/custom-entity-bundle/Entity/Repository/TranslatableCustomEntityRepository.php on line 45

**Comment by jmleroux** [comment]
Hello @ptitkosmos ,

which versions of PIM and extension are you using?

**Comment by ptitkosmos** [comment]
Hello @jmleroux, i'm using Akeneo 2.2.3 and CustomEntities 2.2.0.

But nevermind, this issue is due to a lack in documentation. The extension needs to be defined after PimBundleUI in order to override the ajax controller.

You can close this issue, or retag to MissingDocumentation.

Thanks for your quick reply.

**Comment by jmleroux** [comment]
Thank you for the feedback on the doc!
