### ISSUE TITLE
Modify values before save - Alter values at background

### ISSUE THREAD

**Issue by nilamrz** [akeneo-labs/CustomEntityBundle#183]
Hi,

My custom entity is having 3 fields
```
1. Name
2. Code
3. Label
```

When saving I will only set Name and I will need save in db as  follwing:

```
Code = Name + "XX"
Label = "Label : " + Name
```

Is  there any way to achieve this?

Thanks.

**Comment by mmetayer** [comment]
Hello @nilamrz, you can modify a field before saving by implementing an EventSubscriber (see [here](https://symfony.com/doc/3.4/doctrine/event_listeners_subscribers.html)), or by using lifecycle callbacks (see [here](http://symfony.com/doc/3.4/doctrine/lifecycle_callbacks.html)).
I'll close this issue as it is not directly related to the CustomEntityBundle, feel free to reopen it if you think I was wrong :)

Regards,
Mathias
