### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by danielsimpson** [akeneo-labs/CustomEntityBundle#187]
While trying to create the export job, I get the following:

`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "PimCustomEntityBundle" from namespace "Pim\Bundle\CustomEntityBundle".
Did you forget a "use" statement for another namespace? in /var/www/pim-community-standard/app/AppKernel.php:35
Stack trace:
#0 /var/www/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(494): AppKernel->registerBundles()
#1 /var/www/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(134): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /var/www/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(63): Symfony\Component\HttpKernel\Kernel->boot()
#3 /var/www/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOu in /var/www/pim-community-standard/app/AppKernel.php on line 35`

I have the bundle enabled in app/AppKernel.php like so:

```
public function registerBundles()
    {
        $bundles = $this->registerProjectBundles();

        if (in_array($this->getEnvironment(), array('dev', 'test', 'behat'))) {
            $bundles[] = new \Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Symfony\Bundle\WebServerBundle\WebServerBundle();
        }
```

Any help?

**Comment by danielsimpson** [comment]
Thanks for the quick reply and update @mmetayer , however I'm still seeing similar behavior:

My app/AppKernel.php now:

```
    protected function registerProjectBundles()
    {
        return [
            // your app bundles should be registered here
            new \Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle(),
        ];
    }
```

When creating the export job:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "PimCustomEntityBundle" from namespace "Pim\Bundle\CustomEntityBundle".
Did you forget a "use" statement for another namespace? in /var/www/pim-community-standard/app/AppKernel.php:24
Stack trace:
#0 /var/www/pim-community-standard/app/AppKernel.php(33): AppKernel->registerProjectBundles()
#1 /var/www/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(494): AppKernel->registerBundles()
#2 /var/www/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(134): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#3 /var/www/pim-community-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(63): Symfony\Component\HttpKernel\Kernel->boot()
#4 /var/www/pim-community-standard/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(148): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object in /var/www/pim-community-standard/app/AppKernel.php on line 24
```

**Comment by mmetayer** [comment]
Hello @danielsimpson , this looks like an autoload issue, try to clear your cache and `composer dump-autoload`. If it still doesn't work, you can even try to `composer update`, this should do the trick
