### ISSUE TITLE
Question: Where to place the bundle enabler in AppKernel.php

### ISSUE THREAD

**Issue by vbidou** [akeneo-labs/CustomEntityBundle#192]
Hello and sorry if the question appear stupid, but I cannot find where to add the bundle enabling code inside the AppKernel.php file. I am confused by the description of the Installation.

It says in the method registerProjectBundles, but did I placed it at the right place?

    protected function registerProjectBundles()
    {
        return [
            // your app bundles should be registered here
		new \Pim\Bundle\CustomEntityBundle\PimCustomEntityBundle(),
        ];
    }

Thanks for your advise. Best regards.

**Comment by mmetayer** [comment]
Hello @vbidou, yes, that is exactly where you should place it :)
You also will also have to declare your own bundle there.

Regards,

**Comment by vbidou** [comment]
Merci Matthias pour la confirmation. Very appreciated.
I must confess that I am still struggling, not being a "native" developper, to follow the GitHub deployment menu, and set the stage of the reference data. The process is not easy reading and full of unknown acronyms. Maybe it's much more destinated to dedicated professionals. That's sad because I suppose that many users would like to leverage this powerfull feature. Is there a project on Akeneo side to write up a more comprehensive deployment menu for Akeneo v2.3 ? Thanks for your advise.
