### ISSUE TITLE
History

### ISSUE THREAD

**Issue by PieterCappelle** [akeneo-labs/CustomEntityBundle#201]
Hi,

Every PIM model has a tab "history" but none of them are showing the history? Is this yet implemented or how should this work? Thanks in advance!

**Comment by jmleroux** [comment]
There is no history planned for CutomEntityBundle at this time.
I think it's totally doable in custom code (and PR :wink: ), but we will probably not do it ourselves.

Regards,
JM

**Comment by PieterCappelle** [comment]
Okay, thank you for the answer!
