### ISSUE TITLE
Feature Request: inline creation new object

### ISSUE THREAD

**Issue by userz58** [akeneo-labs/CustomEntityBundle#70]
![2016-04-22 0 04 50](https://cloud.githubusercontent.com/assets/2612186/14724386/6f435b02-081e-11e6-823d-1e2176c97861.png)

can you add this feature for custom entities?

**Comment by fitn** [comment]
Hi @userz58 

We did not plan to add this feature in the CustomEntityBundle so we won't have time on it.

I'm not sure it is easy to do as the Product Edit Form is done on Akeneo PIM side and this behavior will affect the standard PIM behavior which does not manage the Create/Update/Delete feature of reference datas.
Anyway, feel free to contribute on this feature with an optional configuration to create or not reference datas from the product edit view :)

Regards,
