### ISSUE TITLE
Wrong hardcoded ACL name in IndexAction template

### ISSUE THREAD

**Issue by snc** [akeneo-labs/CustomEntityBundle#71]
The ACL `pim_enrich_family_create` is hardcoded in https://github.com/akeneo-labs/CustomEntityBundle/blob/master/Resources/views/CustomEntity/index.html.twig#L15. Shouldn't there be a way to configure it?

**Comment by bOnepain** [comment]
As this issue has been opened for one year, if someone ever had the same problem, here is a workaround that worked for me. You may override the template in your app/Resources/PimCustomEntityBundle/view/CustomEntity/index.html.twig with the following code:
`{% extends baseTemplate %}
{% import 'PimDataGridBundle::macros.html.twig' as dataGrid %}

{% block content %}

    {% set title = (customEntityName ~ ".overview")|trans %}
    {% oro_title_set({params:{'%title%': title}}) %}

    {% set buttons %}
        {% if createUrl|default(false) %}
            {{ elements.createBtn(
                customEntityName,
                createUrl,
                quickCreate ? 'dialog' : '',
                customEntityName ~ '_create',
                'plus'
            ) }}
        {% endif %}
    {% endset %}

    {{ elements.page_header(title, buttons) }}

    {{ dataGrid.renderGrid(customEntityName, { localeCode: locale_code() }) }}

{% endblock %}`

You'll have to make sure your acl identifier is _myCustomEntity_create_
