### ISSUE TITLE
Invalid reference for import/export

### ISSUE THREAD

**Issue by kevinrademan** [akeneo-labs/CustomEntityBundle#86]
When creating a new import job via the UI, the validation always fails with the following error message
```
POST http://docker:9000/job_instance/rest/import/csv_mapping_rule_import

{"configuration":{"reference_data_name":"This value should not be blank.","referenceDataName":"This field was not expected."}}
```

Here is the version of Akeneo im currently running
Edition	CE
Version	1.7.4
Environment	prod
Server version	Apache/2.4.10 (Debian)

After a little digging I found out that the referenceDataName is configured in the following files
https://github.com/akeneo-labs/CustomEntityBundle/blob/master/Resources/config/form_extensions/reference_data_csv_export_edit.yml#L107
https://github.com/akeneo-labs/CustomEntityBundle/blob/master/Resources/config/form_extensions/reference_data_csv_export_show.yml#L102
https://github.com/akeneo-labs/CustomEntityBundle/blob/master/Resources/config/form_extensions/reference_data_csv_import_edit.yml#L118
https://github.com/akeneo-labs/CustomEntityBundle/blob/master/Resources/config/form_extensions/reference_data_csv_import_show.yml#L108

Changing the value from referenceDataName to reference_data_name in those files appears to resolve the problem.

I couldnt figure out how to override those files and I dont want to hack at the vendors folder.
Could you perhaps fix that in your code?

**Comment by fitn** [comment]
Hi @kevinrademan 

Sorry for the delay!
I am working on the problem but the files you provide me seems not the only to change (it still does not work on my side).
Could you make a Pull Request I could test and merge?

Thank you,

**Comment by fitn** [comment]
The version v1.10.2 fixes this issue! :)

**Comment by kevinrademan** [comment]
Somehow the responses on this thread went under the radar on github. 
Thanks allot for the fixes, I really appreciate it. 

PS this project is amazing, keep up the good work
