### ISSUE TITLE
ReferenceData Connector not updated with akeneo 1.7

### ISSUE THREAD

**Issue by jotalops** [akeneo-labs/CustomEntityBundle#89]
the class Pim\Bundle\CustomEntityBundle\Connector\Job\JobParameters\FormConfigurationProvider\ReferenceData continue implementing FormConfigurationProviderInterface that is removed in akeneo 1.7

**Comment by fitn** [comment]
I removed it in the last version 1.10.2.

Thanks to have raised this issue :)
