### ISSUE TITLE
support for akeneo 2.0

### ISSUE THREAD

**Issue by volkovmqx** [akeneo-labs/CustomEntityBundle#96]
Hello there and thanks for the good work,
I saw the PR for the 2.0 compatibility but is there any specific schedule for the release ? 
Thanks.

**Comment by nidup** [comment]
Hi @volkovmqx

Thank you! The 2.0 compatible version is almost complete and will be released in upcoming days.

**Comment by jmleroux** [comment]
First release planned for October 6

**Comment by jmleroux** [comment]
Released as bêta today: https://github.com/akeneo-labs/CustomEntityBundle/pull/94
Stable version will come shortly.
