### ISSUE TITLE
Undefined index: service 

### ISSUE THREAD

**Issue by volkovmqx** [akeneo-labs/CustomEntityBundle#98]
```
Notice: Undefined index: service in 
vendor/akeneo-labs/custom-entity-bundle/Pim/Bundle/CustomEntityBundle/DependencyInjection/Compiler/ConfigurationBuilderPass.php:73
```

dump of the $options array

```

Array
(
    [form_type] => custom_enrich_address
    [enabled] => 1
)
```

EDIT : using the version 2.0 with the CustomEntityBundle 2.0 Beta

**Comment by jmleroux** [comment]
Hello @volkovmqx ,
If you define a key `actions` in your custom entities config, the key `service` is mandatory. It is the service definition of the action to execute.
You can find examples in this file: https://github.com/akeneo-labs/CustomEntityBundle/blob/master/Resources/config/custom_entities.yml

The `action` is not mandatory, like in this file: https://github.com/akeneo-labs/CustomEntityBundle/blob/master/docs/examples/Acme/Bundle/CustomBundle/Resources/config/custom_entities.yml
in this case, the default one are used.
